project:
  type: website
  output-dir: docs

website:
  title: "Laura Kettel"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    toc: false
include-in-header:
  - text: |
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css">

