project:
  type: website
  output-dir: docs

website:
  title: "Your Name"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    toc: false
